### ISSUE TITLE
Feature Req: Badge for multi-module Maven project

### ISSUE THREAD

**Issue by barakugav** [cicirello/jacoco-badge-generator#122]
I have a multi-module Maven project with 4 sub modules. Each of them have its own tests and produce a separate Jacoco report.
I would like to present in my README,md a badge with %coverage of all the Jacoco results together.

Instead of passing a single 'jacoco-csv-file' argument, it would be great to pass a list of files so the badge will present an average coverage weighted by the lines number of each sub module.

Since Jacoco 0.7.7, a goal of 'jacoco:report-aggregate' is supported, which create a single Jacoco report from multiple sub modules.
My problem with this alternative is that it requires an addition dummy sub module which depends on all the other sub modules, and the aggregated Jacoco report is actually the dummy sub module report.
This solution seems a bit messy to me and I want to avoid creating an additional sub module and keep my library cleaner.
Also I do want the reports themselves to be separate, as I prefer each sub module to test itself properly.

Thanks a lot of the tool, love it!

**Comment by barakugav** [comment]
Thanks @cicirello! This is exactly what I needed.
My reports are independent, so that works for me

**Comment by cicirello** [comment]
@barakugav you're welcome
