### ISSUE TITLE
Feature Req: edit workflow summary values

### ISSUE THREAD

**Issue by larskristianhaga** [cicirello/jacoco-badge-generator#131]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, more of an improvement to the summary that is generated after a workflow run.

**Describe the solution you'd like**
I've would like to be able to change the values of the workflow summary. See attached screenshot.

We are generating multiple badges in one workflow, by using `cicirello/jacoco-badge-generator@v2` multiple times on one workflow. And when the workflow is complete it posts a workflow summary with default values, but they all look the same since there is currently no way of customize the summary.

**Describe alternatives you've considered**
Have considered just using separate workflows for generating each badge, but we would still like to customize the values. And we can only find the option to completely turn it off.

**Additional context**
Screenshot:
![image](https://github.com/cicirello/jacoco-badge-generator/assets/13958865/037fd8fd-3eb2-47b5-a926-75c13d8cff39)

**Comment by cicirello** [comment]
I'm assuming you mean to specify a custom heading? That should be easy enough to do. And would definitely make it easy to read for a case like yours since otherwise there isn't a way to distinguish which output is for which module.

**Comment by cicirello** [comment]
@larskristianhaga I can think of at least three alternatives for this. Any thoughts on which one you think might be better?

1. The first option I can think of is to add an action input to allow overriding the current heading of "JaCoCo Test Coverage Summary", and leaving the rest of the formatting as it currently is.
2. The second option I can think of is to actually leave the heading alone, and to use the existing overrides of the left side of the badges in the bullets. E.g., if the left side of the badge was overridden from "coverage" to "coverage (module 1)", then in the workflow job summary to change that bullet to: "coverage (module 1): <percentage>".
3. The third option I can think of is to combine both of the above. Add an input to override the heading of the workflow job summary, and also change the bullets to use the left-side badge overrides.

My intuition is that 1 above is *probably* the way to go. Option 2 won't cover the case where someone didn't override the left side of badges in a multi-module case (e.g., maybe they have the badges in a table in the readme identifying the modules in some other way). And Option 3 seems like it would be redundant (e.g., if the heading is overridden to identify the module, then the current "Coverage" and "Branches" is clear).

What are your thoughts?

**Comment by larskristianhaga** [comment]
Thanks for the detailed options, I agree on your thoughts and think option `1` is the best way to go.

**Comment by cicirello** [comment]
@larskristianhaga just released v2.11.0 also available via major tag v2 with new input for setting the heading of workflow summary. :🚀

**Comment by larskristianhaga** [comment]
Works like a charm, thanks for the quick feedback and implementation!
![image](https://github.com/cicirello/jacoco-badge-generator/assets/13958865/9b22597b-7d9f-4980-8c10-b177dbf496b1)
