### ISSUE TITLE
BUG: An extra __pycache__ file with root permission will break the workflow

### ISSUE THREAD

**Issue by aisensiy** [cicirello/jacoco-badge-generator#46]
**Describe the bug**

The newest version 2.6 will generate a `__pycache__` folder which has a root permission and this will break the next step to remove it without sudo permission.

**To Reproduce**
1. First, '....'
2. Then '....'
3. Finally '....'
4. See error or incorrect behavior, etc.

**Expected behavior**

**Screenshots**

<img width="1735" alt="image" src="https://user-images.githubusercontent.com/661860/154637603-e07f6213-c963-48e0-a13b-65b4f17ef3c8.png">

**Relevant System Info (please complete the following information):**
 - OS
 - Version
 - etc

**Additional context**

**Comment by cicirello** [comment]
@aisensiy I'll suppress the pycache. I'm wondering though if there is something more going on though. I'm not getting the same behavior. Either way I'm going to suppress the pycache. Is this in a public repo? If so do you have a link to the workflow that lead to this error?

**Comment by cicirello** [comment]
@aisensiy Nevermind my question in last comment. I was able to reproduce it. Just wanted to convince myself that there wasn't an additional issue. Will release a fix very soon (already fixed and tested, just need to release).
