### ISSUE TITLE
Question: Badges was not generated

### ISSUE THREAD

**Issue by pablobaldez** [cicirello/jacoco-badge-generator#73]
**Describe the bug**
Maybe it's a beginner question and I'm doing something wrong, but I have a workflow running your action and I can't see the badge in the `read.me` file.

**To Reproduce**
1. Run the workflow build
2. Add the read.me code like the example `![Coverage](https://github.com/pablobaldez/test-coverage-sample/actions/workflows/pr-build.yml/jacoco.svg)`

**Expected behavior**
I was expecting to see the badge such as the build badge

**Screenshots**
here is how my read me is
![Screenshot 2022-06-30 at 21 16 24](https://user-images.githubusercontent.com/7607311/176759788-b3869854-f00d-48b7-b1cd-7c0c4529cb36.png)

**Additional context**
here is my GitHub repository if you want to check more details https://github.com/pablobaldez/test-coverage-sample

**Comment by cicirello** [comment]
@pablobaldez I looked at your workflow. And it doesn't look like you have a step to commit and push the badges. The jacoco-badge-generator doesn't commit the badges. There are a variety of ways that you can do this. The sample workflows show a couple of these. [Example workflow 1](https://github.com/cicirello/jacoco-badge-generator#example-workflow-1-generate-instructions-or-c0-coverage-badge-only) has a step (next to the last step) that uses git directly with a simple shell script. [Example workflow 2](https://github.com/cicirello/jacoco-badge-generator#example-workflow-2-generate-instructions-coverage-and-branches-coverage-badges) uses another action for this (next to the last step), specifically, the [EndBug/add-and-commit](https://github.com/EndBug/add-and-commit) action.

Here are just those steps from the sample workflows.

With a shell script (fill in missing details... your name and email):
```YAML
    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain *.svg` ]]; then
          git config --global user.name 'YOUR NAME HERE'
          git config --global user.email 'YOUR-GITHUB-USERID@users.noreply.github.com'
          git add -A *.svg
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push *.svg
        fi
```

Or with the [EndBug/add-and-commit](https://github.com/EndBug/add-and-commit) action:
```YAML
    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'commit badge'
        add: '*.svg'
```

Let me know how one of these works out for you.

**Comment by pablobaldez** [comment]
@cicirello thank you for your response. I just added the ` EndBug/add-and-commit@v7` and it's working now.

**Comment by cicirello** [comment]
@pablobaldez great.
