### ISSUE TITLE
Replace the use of GitHub Action's deprecated set-output 

### ISSUE THREAD

**Issue by cicirello** [cicirello/jacoco-badge-generator#84]
**Describe the bug**
GitHub Actions has deprecated the set-output workflow command, which we are currently using for workflow outputs of the action. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. That same link indicates the replacement. 

**To Reproduce**
1. Run the action.
2. Inspect the workflow run.
3. Notice the deprecation warning.

**Expected behavior**
No deprecation warning.

**Comment by erodewald** [comment]
Unfortunately, this is going to break usage for self-hosted GHES enterprise organizations that are not on the bleeding edge. I am still on GHES 3.5, which uses runner version `2.294.0` while this requires at least `2.297.0`. I am going to have to pin to `2.7.0` if reverting is not possible.

**Comment by cicirello** [comment]
@erodewald does your workflow use those outputs in later steps? If not, then it shouldn't break it in your case. I have a check in there if the new environment variable exists. The original purpose of the check was for the case of someone using it as a CLI tool entirely outside of Actions.

If you are using those outputs, I think I can probably use the old `set-output` if the new environment variable doesn't exist.

**Comment by cicirello** [comment]
@erodewald I had some time to look at it, so rather than wait for an answer to my previous question, I assumed that it would likely break things for someone. The newly released version v2.8.1 should fix it. It will use the new approach if GitHub's new environment variable exists, and will otherwise use the deprecated `set-output` (PR #91).

**Comment by erodewald** [comment]
Apologies for the delay. I do use the output in a follow-up step. Thanks for offering the fallback patch! 👍

**Comment by cicirello** [comment]
@erodewald let me know if there are any issues with the patch. I had to fake running in actions on my local machine to test it, since any testing on GitHub would pick up the new env file.

**Comment by erodewald** [comment]
@cicirello I'm seeing positive results from numerous PRs that are using `@v2`: 

Runner: 
```
Current runner version: '2.294.0'
```

Action fetch looks good 👍 (confirming that v2 sha points to 2.8.1)
```
Download action repository 'cicirello/jacoco-badge-generator@v2' (SHA:2dc380ee1533a13cd53ac62743c847842212407b)
##[debug]Download 'https://api.github.com/repos/cicirello/jacoco-badge-generator/tarball/2dc380ee1533a13cd53ac62743c847842212407b' to '/runner/_work/_actions/_temp_593b2a2e-4a3c-473e-a528-f1c46c6cb392/b6cf47c3-a6cb-4fb5-a673-5451f23dfd3c.tar.gz'
```

Action debug output looks good 👍 
```shell
::set-output name=coverage::0.9122481442205727
##[debug]steps.jacoco.outputs.coverage='0.9122481442205727'
::set-output name=branches::0.6594202898550725
##[debug]steps.jacoco.outputs.branches='0.6594202898550725'
##[debug]Docker Action run completed with exit code 0
```
Output usage succeeded as well. 👍 

Thanks.

**Comment by cicirello** [comment]
@erodewald great. Thanks for sharing.
